[package]
name = "sparse_matrix"
version = "0.1.0"
authors = ["Kevin Tran <kevintran@airmail.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
rayon = "1.4.0"
rand = "0.7.3"
quickcheck = "0.9.2"

[dev-dependencies]
quickcheck_macros = "0.9.1"
criterion = "0.3.3"

[[bench]]
name = "my_bench"
harness = false

[profile.release]
debug = true